quando uso o += a mesma referencia e utilizada, logo o array e modificado

In [4]:
import numpy as np

a = np.array([1,2,3,4])
b = a
a += np.array([1,1,1,1,])
print b



[2 3 4 5]


Nesse caso, quando eu faco a atribuicao apos, e criado um novo array, logo quando vou imprimir o array b, ele esta com o endereco de memoria do primeiro a que lhe foi passado como referencia

In [7]:
import numpy as np
a = np.array([1,2,3,4])
b = a
a  = a + np.array([1,1,1,1])
print b

[1 2 3 4]


O numpy utiliza a mesma posicao de memoria do array original, entao se precisamos modifica-lo devemos ter muito cuidado. Ele faz apenas uma referencia a array original, por isso suas operacoes sao mais rapidas, nao e preciso criar ou copiar valores a um novo array


In [8]:
import numpy as np
a = np.array([1,2,3,4,5])
slice = a[:3]
slice[0]=100
print a

[100   2   3   4   5]
